import './globals.css'
import type { Metadata } from 'next'
import { Inter , Roboto , Montserrat} from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const roboto = Roboto ({
  weight: ['400' , '700'],
  subsets: ['latin']
})

export const monstserrat =  Montserrat({
  subsets: ['latin'],
  weight: ['200' , '300' , '500']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
